using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace UltimateBannerMerging
{
    internal static class MobBanners
    {
        public static Banner[] Banners = new Banner[]
        {
            new Banner(1683, "Blue Slime"),
            new Banner(2928, "Green Slime"),
            new Banner(2964, "Purple Slime"),
            new Banner(2960, "Pinky"),
            new Banner(1701, "Zombie"),
            new Banner(1639, "Demon Eye"),
            new Banner(1655, "Goblin Scout"),
            new Banner(1658, "Harpy"),
            new Banner(1634, "Crab"),
            new Banner(3447, "Pink Jellyfish"),
            new Banner(3594, "Sea Snail"),
            new Banner(1680, "Shark"),
            new Banner(2983, "Squid"),
            new Banner(1669, "Meteor Head"),
            new Banner(2962, "Possessed Armor"),
            new Banner(1699, "Wraith"),
            new Banner(1695, "Werewolf"),
            new Banner(1700, "Wyvern"),
            new Banner(2968, "Red Slime"),
            new Banner(2992, "Yellow Slime"),
            new Banner(2899, "Black Slime"),
            new Banner(2955, "Mother Slime"),
            new Banner(1621, "Cave Bat"),
            new Banner(2906, "Cochineal Beetle"),
            new Banner(3393, "Crawdad"),
            new Banner(3392, "Giant Shelly"),
            new Banner(1698, "Worm"),
            new Banner(1694, "Nymph"),
            new Banner(3391, "Salamander"),
            new Banner(1681, "Skeleton"),
            new Banner(2986, "Tim"),
            new Banner(2987, "Undead Miner"),
            new Banner(1665, "Blue Jellyfish"),
            new Banner(1689, "Toxic Sludge"),
            new Banner(1620, "Armored Skeleton"),
            new Banner(2923, "Giant Bat"),
            new Banner(1630, "Mimic"),
            new Banner(2969, "Rune Wizard"),
            new Banner(2973, "Skeleton Archer"),
            new Banner(1615, "Angler Fish"),
            new Banner(3448, "Green Jellyfish"),
            new Banner(3407, "Granite Elemental"),
            new Banner(3408, "Granite Golem"),
            new Banner(3406, "Hoplite"),
            new Banner(3405, "Medusa"),
            new Banner(1685, "Wall Creeper"),
            new Banner(1623, "Black Recluse"),
            new Banner(1617, "Anomura Fungus"),
            new Banner(1649, "Fungi Bulb"),
            new Banner(1672, "Mushi Ladybug"),
            new Banner(1686, "Spore Zombie"),
            new Banner(1650, "Fungo Fish"),
            new Banner(2935, "Ice Slime"),
            new Banner(2980, "Spiked Ice Slime"),
            new Banner(2912, "Cyan Beetle"),
            new Banner(2933, "Ice Bat"),
            new Banner(2959, "Penguin"),
            new Banner(1684, "Snow Flinx"),
            new Banner(2988, "Undead Viking"),
            new Banner(1643, "Frozen Zombie"),
            new Banner(2898, "Armored Viking"),
            new Banner(1662, "Ice Elemental"),
            new Banner(3452, "Ice Tortoise"),
            new Banner(1663, "Icy Merman"),
            new Banner(1674, "Pigron"),
            new Banner(1696, "Wolf"),
            new Banner(2940, "Jungle Slime Banner"),
            new Banner(2981, "Spiked Jungle Slime"),
            new Banner(2915, "Doctor Bones"),
            new Banner(1661, "Hornet"),
            new Banner(2939, "Jungle Bat"),
            new Banner(2942, "Lac Beetle"),
            new Banner(1668, "Man Eater"),
            new Banner(2977, "Snatcher"),
            new Banner(1675, "Piranha"),
            new Banner(2897, "Angry Trapper"),
            new Banner(1640, "Derpling"),
            new Banner(2925, "Giant Flying Fox"),
            new Banner(1688, "Giant Tortoise"),
            new Banner(1666, "Jungle Creeper"),
            new Banner(1670, "Moth"),
            new Banner(1619, "Arapaima"),
            new Banner(1647, "Flying Snake"),
            new Banner(1667, "Lihzahrd"),
            new Banner(3593, "Sand Slime"),
            new Banner(1618, "Antlion"),
            new Banner(3414, "Antlion Charger"),
            new Banner(3413, "Antlion Swarmer"),
            new Banner(3411, "Tomb Crawler"),
            new Banner(1693, "Vulture"),
            new Banner(3418, "Basilisk"),
            new Banner(3417, "Desert Spirit"),
            new Banner(3412, "Dune Splicer"),
            new Banner(3415, "Ghoul"),
            new Banner(3416, "Lamia"),
            new Banner(1671, "Mummy"),
            new Banner(3419, "Sand Poacher"),
            new Banner(2944, "Lava Slime"),
            new Banner(1627, "Bone Serpent"),
            new Banner(1638, "Demon"),
            new Banner(1664, "Fire Imp"),
            new Banner(1659, "Hellbat"),
            new Banner(2943, "Lava Bat"),
            new Banner(3446, "Red Devil"),
            new Banner(3451, "Angry Bones"),
            new Banner(2911, "Cursed Skull"),
            new Banner(1682, "Dark Caster"),
            new Banner(2916, "Dungeon Slime"),
            new Banner(2900, "Blue Armored Bones"),
            new Banner(2970, "Rusty Armored Bones"),
            new Banner(2930, "Hell Armored Bones"),
            new Banner(2914, "Diabolist"),
            new Banner(2956, "Necromancer"),
            new Banner(2965, "Ragged Caster"),
            new Banner(2904, "Bone Lee"),
            new Banner(2974, "Skeleton Commando"),
            new Banner(2975, "Skeleton Sniper"),
            new Banner(2984, "Tactical Skeleton"),
            new Banner(2917, "Dungeon Spirit"),
            new Banner(2924, "Giant Cursed Skull"),
            new Banner(2958, "Paladin"),
            new Banner(2913, "Devourer"),
            new Banner(1641, "Eater of Souls"),
            new Banner(2908, "Corrupt Slime"),
            new Banner(2976, "Slimer"),
            new Banner(2905, "Clinger"),
            new Banner(2909, "Corruptor"),
            new Banner(1637, "Cursed Hammer"),
            new Banner(3449, "Dark Mummy"),
            new Banner(1697, "World Feeder"),
            new Banner(1626, "Blood Crawler"),
            new Banner(1635, "Crimera"),
            new Banner(1644, "Face Monster"),
            new Banner(2910, "Crimslime"),
            new Banner(1624, "Blood Feeder"),
            new Banner(1625, "Blood Jelly"),
            new Banner(1636, "Crimson Axe"),
            new Banner(1645, "Floaty Gross"),
            new Banner(1660, "Herpling"),
            new Banner(2936, "Ichor Sticker"),
            new Banner(1629, "Chaos Elemental"),
            new Banner(1642, "Enchanted Sword"),
            new Banner(2937, "Illuminant Bat"),
            new Banner(3450, "Light Mummy"),
            new Banner(1677, "Pixie"),
            new Banner(1691, "Unicorn"),
            new Banner(1651, "Gastropod"),
            new Banner(2938, "Illuminant Slime"),
            new Banner(1690, "Umbrella Slime"),
            new Banner(1646, "Flying Fish"),
            new Banner(1678, "Raincoat Zombie"),
            new Banner(2966, "Rainbow Slime"),
            new Banner(1616, "Angry Nimbus"),
            new Banner(2934, "Ice Golem"),
            new Banner(3409, "Blood Zombie"),
            new Banner(1632, "Corrupt Bunny"),
            new Banner(1633, "Corrupt Goldfish"),
            new Banner(2907, "Corrupt Penguin"),
            new Banner(3410, "Drippler"),
            new Banner(2985, "The Groom"),
            new Banner(1631, "Clown"),
            new Banner(2927, "Goblin Archer"),
            new Banner(1654, "Goblin Peon"),
            new Banner(1653, "Goblin Sorcerer"),
            new Banner(1652, "Goblin Thief"),
            new Banner(1656, "Goblin Warrior"),
            new Banner(3390, "Goblin Summoner"),
            new Banner(3793, "Angry Tumbler"),
            new Banner(3789, "Sand Shark"),
            new Banner(3780, "Sand Elemental"),
            new Banner(3792, "Crystal Thresher"),
            new Banner(3790, "Bone Biter"),
            new Banner(3791, "Flesh Reaver"),
            new Banner(1673, "Parrot Banner"),
            new Banner(3441, "Pirate Captain"),
            new Banner(3443, "Pirate Corsair"),
            new Banner(3444, "Pirate Crossbower"),
            new Banner(3442, "Pirate Deadeye"),
            new Banner(1676, "Pirate Deckhand"),
            new Banner(3400, "Butcher Banner"),
            new Banner(3395, "Creature from the Deep"),
            new Banner(3402, "Deadly Sphere"),
            new Banner(3396, "Dr. Man Fly"),
            new Banner(2920, "Eyezor"),
            new Banner(1648, "Frankenstein"),
            new Banner(3394, "Fritz"),
            new Banner(3397, "Mothron"),
            new Banner(3403, "Nailhead"),
            new Banner(3401, "Psycho"),
            new Banner(1679, "Reaper"),
            new Banner(1687, "Swamp Thing"),
            new Banner(3399, "The Possessed"),
            new Banner(1692, "Vampire"),
            new Banner(2929, "Headless Horseman"),
            new Banner(2931, "Hellhound"),
            new Banner(2961, "Poltergeist"),
            new Banner(2971, "Scarecrow"),
            new Banner(2982, "Splinterling"),
            new Banner(2918, "Elf Archer"),
            new Banner(2919, "Elf Copter"),
            new Banner(2921, "Flocko"),
            new Banner(2926, "Gingerbread Man"),
            new Banner(2941, "Krampus"),
            new Banner(2957, "Nutcracker"),
            new Banner(2963, "Present Mimic"),
            new Banner(2993, "Yeti"),
            new Banner(2994, "Zombie Elf"),
            new Banner(2945, "Martian Brainscrambler"),
            new Banner(2946, "Martian Drone"),
            new Banner(2947, "Martian Engineer"),
            new Banner(2948, "Martian Gigazapper"),
            new Banner(2949, "Martian Gray Grunt"),
            new Banner(2950, "Martian Officer"),
            new Banner(2951, "Martian Ray Gunner"),
            new Banner(2952, "Martian Scutlix Gunner"),
            new Banner(2953, "Martian Tesla Turret"),
            new Banner(3445, "Martian Walker"),
            new Banner(2972, "Scutlix"),
            new Banner(3438, "Alien Hornet"),
            new Banner(3436, "Alien Larva"),
            new Banner(3437, "Alien Queen"),
            new Banner(3440, "Storm Diver"),
            new Banner(3439, "Vortexian"),
            new Banner(3433, "Brain Suckler"),
            new Banner(3435, "Evolution Beast"),
            new Banner(3434, "Nebula Floater"),
            new Banner(3432, "Predictor"),
            new Banner(3422, "Flow Invader"),
            new Banner(3421, "Milkyway Weaver"),
            new Banner(3425, "Star Cell"),
            new Banner(3420, "Stargazer"),
            new Banner(3423, "Twinkle Popper"),
            new Banner(3426, "Corite"),
            new Banner(3428, "Crawltipede"),
            new Banner(3430, "Drakomire"),
            new Banner(3429, "Drakomire Rider"),
            new Banner(3431, "Selenian"),
            new Banner(3427, "Sroller")
        };
        public static Banner GetBannerByID(int id)
        {
            return Banners.FirstOrDefault(b => b.ID == id);
        }
        public static Banner GetBannerByMobName(string name)
        {
            return Banners.FirstOrDefault(b => b.Name == name);
        }
    }
    internal class Banner
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Banner(int id, string name)
        {
            ID = id;
            Name = name;
        }
    }
}
